declare module org.ssatguru.babylonjs.component {
    import Camera = BABYLON.Camera;
    import LinesMesh = BABYLON.LinesMesh;
    import Mesh = BABYLON.Mesh;
    import Vector3 = BABYLON.Vector3;
    class EditControl {
        private meshPicked;
        canvas: HTMLCanvasElement;
        private scene;
        private mainCamera;
        private theParent;
        private local;
        private snapT;
        private snapR;
        private transSnap;
        private rotSnap;
        private axesLen;
        private axesScale;
        private redMat;
        private greenMat;
        private blueMat;
        private whiteMat;
        private yellowMat;
        constructor(mesh: Mesh, camera: Camera, canvas: HTMLCanvasElement, scale: number);
        private renderLoopProcess();
        switchTo(mesh: Mesh): void;
        detach(): void;
        pDown: boolean;
        axisPicked: Mesh;
        private onPointerDown(evt);
        isEditing(): boolean;
        private detachControl(cam, can);
        private prevOverMesh;
        private onPointerOver();
        editing: boolean;
        private onPointerUp(evt);
        prevPos: Vector3;
        snapX: number;
        snapY: number;
        snapZ: number;
        snapRX: number;
        snapRY: number;
        snapRZ: number;
        private onPointerMove(evt);
        private doTranslation(newPos);
        private doScaling(newPos);
        private doRotation(newPos);
        private getPosOnPickPlane();
        private hideBaxis();
        private setAxisVisiblity(v);
        private transEnabled;
        enableTranslation(): void;
        disableTranslation(): void;
        private rotEnabled;
        enableRotation(): void;
        disableRotation(): void;
        private scaleEnabled;
        enableScaling(): void;
        disableScaling(): void;
        private bXaxis;
        private bYaxis;
        private bZaxis;
        private xaxis;
        private yaxis;
        private zaxis;
        private guideCtl;
        private createGuideAxes();
        private pickPlane;
        private createPickPlane();
        private tCtl;
        private tX;
        private tY;
        private tZ;
        private tEndX;
        private tEndY;
        private tEndZ;
        private createTransAxes();
        rCtl: Mesh;
        rX: Mesh;
        rY: Mesh;
        rZ: Mesh;
        rEndX: LinesMesh;
        rEndY: LinesMesh;
        rEndZ: LinesMesh;
        private createRotAxes();
        private extrudeBox(w, l);
        private createCircle(r);
        private sCtl;
        private sX;
        private sY;
        private sZ;
        private sAll;
        private sEndX;
        private sEndY;
        private sEndZ;
        private sEndAll;
        private createScaleAxes();
        localX: Vector3;
        localY: Vector3;
        localZ: Vector3;
        localRot: Vector3;
        private setLocalAxes(mesh);
        setLocal(l: boolean): void;
        setTransSnap(s: boolean): void;
        setRotSnap(s: boolean): void;
        setTransSnapValue(t: number): void;
        setRotSnapValue(r: number): void;
        private setAxesScale();
        static getAngle(p1: Vector3, p2: Vector3, p: Vector3, cN: Vector3): number;
        private createMaterials(scene);
        private disposeMaterials();
        private static getStandardMaterial(name, col, scene);
    }
}
